import { BaseAgent } from "./base-agent.ts";
import type {
  AgentMentionEvent,
  AgentScanEvent,
  AgentThreadCreatedEvent,
} from "./types.ts";
import type { Thread } from "../thread-store.ts";

export class SreAgent extends BaseAgent {
  readonly name = "sre-agent";

  override async onThreadCreated(event: AgentThreadCreatedEvent): Promise<void> {
    const { thread } = event;
    if (!thread.tags.includes("incident")) return;

    await this.updatePresence(thread, "active", "Incident response");

    await this.addComment(
      thread,
      `**Incident checklist** (auto-generated by sre-agent)\n\n` +
        `- [ ] Identify affected services\n` +
        `- [ ] Assess severity (P1/P2/P3)\n` +
        `- [ ] Notify on-call team\n` +
        `- [ ] Begin mitigation\n` +
        `- [ ] Document timeline\n` +
        `- [ ] Post-mortem scheduled\n\n` +
        `Mention \`@sre-agent\` for a status assessment at any time.`
    );
  }

  override async onMention(event: AgentMentionEvent): Promise<void> {
    const { thread, comment } = event;

    await this.updatePresence(thread, "assessing", "Status assessment requested");

    const status = thread.status;
    const tags = thread.tags.join(", ") || "none";
    const age = this.getThreadAge(thread);

    await this.addComment(
      thread,
      `**SRE Status Assessment** (requested by ${comment.actor})\n\n` +
        `- **Status:** ${status}\n` +
        `- **Tags:** ${tags}\n` +
        `- **Thread age:** ${age}\n` +
        `- **Current state:** ${this.assessState(thread)}\n\n` +
        `_Reply with more context or mention \`@sre-agent\` again for an updated assessment._`
    );
  }

  override async onScan(event: AgentScanEvent): Promise<void> {
    const { thread, reason } = event;
    if (!thread.tags.includes("incident") && !thread.tags.includes("infra")) return;

    await this.addComment(
      thread,
      `**SRE scan notice** — ${reason}\n\nPlease review this thread's current status.`
    );
  }

  private getThreadAge(thread: Thread): string {
    const created = new Date(thread.createdAt).getTime();
    const now = Date.now();
    const minutes = Math.floor((now - created) / 60_000);
    if (minutes < 60) return `${minutes}m`;
    const hours = Math.floor(minutes / 60);
    if (hours < 24) return `${hours}h ${minutes % 60}m`;
    return `${Math.floor(hours / 24)}d ${hours % 24}h`;
  }

  private assessState(thread: Thread): string {
    if (thread.status === "escalated") return "ESCALATED — needs immediate attention";
    if (thread.status === "in_progress") return "Being worked on";
    if (thread.status === "resolved") return "Resolved";
    return "Open — awaiting triage or action";
  }
}
